import '../styles/globals.scss'
import LayoutProvider from "@/components/LayoutProvider";
import ReactQueryProvider from "@/app/ReactQueryProvider";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <LayoutProvider>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </LayoutProvider>
      </body>
    </html>
  )
}
